name: release

on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    if: ${{ github.repository_owner == 'dragidavid' }}
    name: release
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v4
        name: install pnpm
        id: pnpm-install
        with:
          version: 10.9.0
          run_install: false

      - name: install node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - name: install dependencies
        run: pnpm install

      - name: build the package
        run: pnpm aura:build

      - name: create release pr or publish to npm
        id: changesets
        uses: changesets/action@v1
        with:
          commit: "chore(release): version packages"
          title: "chore(release): version packages"
          version: node .github/changeset-version.js
          publish: npx changeset publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NODE_ENV: "production"
